/**
 * Seznam českých fotbalových klubů pro autocomplete při registraci
 */

export const CZECH_FOOTBALL_CLUBS: string[] = [
  'AC Sparta Praha',
  'SK Slavia Praha',
  'FC Viktoria Plzeň',
  'FC Baník Ostrava',
  'FK Mladá Boleslav',
  '1. FC Slovácko',
  'FC Slovan Liberec',
  'SK Sigma Olomouc',
  'FC Hradec Králové',
  'FK Teplice',
  'Bohemians Praha 1905',
  'FK Jablonec',
  'FK Pardubice',
  'MFK Karviná',
  'FC Zlín',
  'FC Trinity Zlín',
  'SK Dynamo České Budějovice',
  'FK Dukla Praha',
  'FC Zbrojovka Brno',
  'FC Vysočina Jihlava',
  'FC Silon Táborsko',
  'FC Viktoria Žižkov',
  'FK Ústí nad Labem',
  'FK Varnsdorf',
  'SK Líšeň',
  'FC MAS Táborsko',
  'FC Slavia Karlovy Vary',
  'FK Chmel Blšany',
  '1. FK Příbram',
  'FC Graffin Vlašim',
  'FK Králův Dvůr',
  'FK Kolín',
  'FK Dobrovice',
  'FC Sellier & Bellot Vlašim',
  'SK Hanácká Slavia Kroměříž',
  'FK Fotbal Třinec',
  'FC Vítkovice',
  'FK Slavoj Vyšehrad',
].sort((a, b) => a.localeCompare(b, 'cs'));
